"""add new column to books table

Revision ID: d63ab3a5d015
Revises: 4c0ad765d91f
Create Date: 2025-10-25 12:21:28.843442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63ab3a5d015'
down_revision = '4c0ad765d91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('test_something', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'test_something')
    # ### end Alembic commands ###
